CREATE SCHEMA STATBOT_DB;

SET search_path TO STATBOT_DB;

CREATE TABLE SERVERS
(ServerID		BIGINT,
Importing	 	BOOL DEFAULT TRUE,
ImportHistory	BOOL DEFAULT FALSE,
PRIMARY KEY(ServerID));

CREATE TABLE CHANNELS
(ChannelID	BIGINT,
ServerID	BIGINT	NOT NULL,
Importing	BOOL	DEFAULT TRUE,
PRIMARY KEY(ChannelID),
FOREIGN KEY(ServerID) REFERENCES SERVERS(ServerID)
       ON DELETE CASCADE
       ON UPDATE CASCADE);

CREATE TABLE USERS
(UserID		BIGINT,
Restricted	BOOL DEFAULT FALSE,
PRIMARY KEY(UserID));

CREATE TABLE HAS_USERS
(ServerID		BIGINT,
UserID			BIGINT,
PRIMARY KEY(ServerID, UserID),
FOREIGN KEY(ServerID) REFERENCES SERVERS(ServerID)
       ON DELETE CASCADE
       ON UPDATE CASCADE,
FOREIGN KEY(UserID) REFERENCES USERS(UserID)
       ON DELETE CASCADE
       ON UPDATE CASCADE);

CREATE TABLE MESSAGES
(MessageID		BIGINT,
Reference		BIGINT,
Content			VARCHAR(2000)		NOT NULL,
AttachmentURLS	TEXT[]				NOT NULL,
Sent			TIMESTAMPTZ			NOT NULL,
EditTime		TIMESTAMPTZ,
ServerID		BIGINT				NOT NULL,
ChannelID		BIGINT				NOT NULL,
AuthorID		BIGINT				NOT NULL,
PRIMARY KEY(MessageID),
FOREIGN KEY(ServerID) REFERENCES SERVERS(ServerID)
       ON DELETE CASCADE
       ON UPDATE CASCADE,
FOREIGN KEY(ChannelID) REFERENCES CHANNELS(ChannelID)
       ON DELETE CASCADE
       ON UPDATE CASCADE);

CREATE INDEX idx_MESSAGES_AuthorID
ON MESSAGES (AuthorID);
